resources:
- mysql/deployment.yaml
- mysql/service.yaml
- mysql/pvc.yaml
- wordpress/deployment.yaml
- wordpress/service.yaml
- wordpress/pvc.yaml
- wordpress/hpa.yaml
- storageclass-azure.yaml

commonAnnotations:
  app: demo

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: demo